#!/bin/sh

#echo Content-type: text/html
#echo

echo '<html>'
echo '<head>'
echo '<meta http-equiv="Content-Type"'
echo 'content="text/html; charset=iso-8859-1">'
echo '<LINK REL=stylesheet HREF="/html4.css">'
echo '<title>Beveridge Hosting Ping Utility</title>'
echo '</head>'

echo '<body>'

echo '<h1>Beveridge Hosting Ping Utility</h1>'

echo '<hr>'

echo "<p>Use this form to ping a host from the bevhost.net"
echo 'Server.</p>'

echo '<form action="/cgi-bin/nph-ping" method="GET"'
echo '    <p>Enter the hostname or IP address to ping in the space'
echo '    provided below.</p>'
echo '    <blockquote>'
echo '        <p><input type="text" size="50" maxlength="50"'
echo '        name="data"> <br>'
echo '        </p>'
echo '    </blockquote>'
echo '    <p><input type="submit" value="Submit Form"> <input'
echo '    type="reset" value="Reset Form"> </p>'
echo '</form>'

HOST=`echo $QUERY_STRING | gawk  '/data=/ { print $1 }' | cut -f2 -d= | sed s/%3A/:/g`
if [ $HOST ]
then
   echo '<hr>'
   echo "<h3>Results for $HOST</h3>"
   echo '<pre>'
   host -ta $HOST
   /bin/ping -s 50 -c 4 $HOST
   host -taaaa $HOST
   /bin/ping6 -s 50 -c 4 $HOST
   echo '</pre>'
fi
echo '<hr><a href="http://www.bevhost.com">www.bevhost.com</a> <a href="/">Other Tools</a>'
echo '</body>'
echo '</html>'

