#!/bin/bash

#echo Content-type: text/html
#echo

echo '<html>'
echo '<head>'
echo '<meta http-equiv="Content-Type"'
echo 'content="text/html; charset=iso-8859-1">'
echo '<LINK REL=stylesheet HREF="/html4.css">'
echo '<title>Beveridge Hosting TraceRoute Utility</title>'
echo '</head>'

echo '<body>'

echo '<h1>Beveridge Hosting TraceRoute Utility</h1>'

echo '<hr>'

echo "<p>Use this form to trace the route to a host from the bevhost.net"
echo 'Server.</p>'

echo '<form action="/cgi-bin/nph-trace" method="GET"'
echo '    <p>Enter the hostname or IP address to trace in the space'
echo '    provided below.</p>'
echo '    <blockquote>'
echo '        <p><input type="text" size="50" maxlength="50"'
echo '        name="data"> <br>'
echo '        </p>'
echo '    </blockquote>'
echo '    <p><input type="submit" value="Submit Form"> <input'
echo '    type="reset" value="Reset Form"> </p>'
echo '</form>'

echo '<hr>'
HOST=`echo $QUERY_STRING | gawk  '/data=/ { print $1 }' | cut -f2 -d=  | sed s/%3A/:/g`
if [ $HOST ]
then
   echo "<h3>Results for $HOST</h3>"
   echo '<pre>'
   traceroute -I -w 3 $HOST -A 2>&1
   echo '</pre>'
fi
echo '<hr><a href="http://www.bevhost.com">www.bevhost.com</a> <a href="/">Other Tools</a>'
echo '</body>'
echo '</html>'
